# Generated by Django 4.1.4 on 2023-02-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'verbose_name': 'Продукт на складе', 'verbose_name_plural': 'Продукты на складах'},
        ),
    ]
